In [159]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [160]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import torch.nn.functional as F
import torch.nn as nn
import torch.optim as optim
import networkx as nx
import scipy as sp

In [161]:
import utils, dlqr

In [162]:
a = torch.arange(5)
a

tensor([0, 1, 2, 3, 4])

In [163]:
b = a.detach().clone()
b

tensor([0, 1, 2, 3, 4])

In [164]:
b[1] = 10

In [93]:
b

tensor([ 0, 10,  2,  3,  4])

In [94]:
a

tensor([0, 1, 2, 3, 4])

In [96]:
a

tensor([0, 1, 2, 3, 4])

In [110]:
G, S, A, B, Q, R = dlqr.generate_lq_env(10, 5, 'cpu')

In [113]:
S.requires_grad_(True) / torch.max(S)

tensor([[1., 1., 1., 0., 0., 0., 1., 0., 0., 1.],
        [1., 1., 1., 0., 0., 0., 1., 0., 0., 1.],
        [1., 1., 1., 0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1., 0., 1., 1., 0.],
        [0., 0., 0., 1., 1., 1., 0., 1., 1., 0.],
        [0., 0., 0., 1., 1., 1., 0., 1., 1., 0.],
        [1., 1., 1., 0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 0., 0., 0., 1., 1., 1., 1.]], dtype=torch.float64,
       grad_fn=<DivBackward0>)

In [119]:
xx = torch.rand(S.shape, dtype=torch.double)
a = torch.norm(S @ xx)
a.backward()

In [120]:
S.grad

tensor([[1.1561, 1.0225, 1.1192, 0.4667, 0.3085, 0.3884, 1.0298, 0.4830, 0.3431,
         1.1709],
        [1.1561, 1.0225, 1.1192, 0.4667, 0.3085, 0.3884, 1.0298, 0.4830, 0.3431,
         1.1709],
        [1.3743, 1.1717, 1.2687, 0.6583, 0.4484, 0.5119, 1.1636, 1.3389, 1.1577,
         1.3462],
        [0.5003, 0.3347, 0.3946, 1.0902, 0.9468, 0.9752, 0.3264, 1.1154, 1.0101,
         0.4338],
        [0.5003, 0.3347, 0.3946, 1.0902, 0.9468, 0.9752, 0.3264, 1.1154, 1.0101,
         0.4338],
        [0.5003, 0.3347, 0.3946, 1.0902, 0.9468, 0.9752, 0.3264, 1.1154, 1.0101,
         0.4338],
        [1.3743, 1.1717, 1.2687, 0.6583, 0.4484, 0.5119, 1.1636, 1.3389, 1.1577,
         1.3462],
        [0.7907, 0.5609, 1.3400, 1.3708, 1.1136, 1.2238, 1.2025, 1.4002, 1.1839,
         1.4155],
        [0.7907, 0.5609, 1.3400, 1.3708, 1.1136, 1.2238, 1.2025, 1.4002, 1.1839,
         1.4155],
        [1.3743, 1.1717, 1.2687, 0.6583, 0.4484, 0.5119, 1.1636, 1.3389, 1.1577,
         1.3462]], dtype=tor

In [151]:
S = torch.eye(3, dtype=torch.double).requires_grad_(True)
S_inds = (S != 0)
xx = torch.rand(S.shape, dtype=torch.double)

In [158]:
S[S_inds]

tensor([1., 1., 1.], dtype=torch.float64, grad_fn=<IndexBackward>)

In [152]:
torch.norm(torch.tanh((S @ xx)) @ xx).backward()

In [153]:
S.grad

tensor([[0.3368, 0.4895, 0.3032],
        [0.5111, 0.4876, 0.4780],
        [0.3784, 0.5265, 0.3250]], dtype=torch.float64)

In [155]:
ss = torch.ones(3, dtype=torch.double).requires_grad_(True)
smat = torch.zeros(S.shape, dtype=torch.double)
smat[S_inds] = ss

In [156]:
torch.norm(torch.tanh((smat @ xx)) @ xx).backward()

In [157]:
ss.grad

tensor([0.3368, 0.4876, 0.3250], dtype=torch.float64)